---
ENABLE_LINTERS:
  - ANSIBLE_ANSIBLE_LINT
  - BASH_EXEC
  - BASH_SHELLCHECK
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWNLINT
  - SPELL_MISSPELL
  - SPELL_PROSELINT
  - SPELL_VALE
  - YAML_YAMLLINT

SARIF_REPORTER: true
SHOW_ELAPSED_TIME: true
EDITORCONFIG_EDITORCONFIG_CHECKER_CONFIG_FILE: '.ecrc.json'

ANSIBLE_ANSIBLE_LINT_FILE_EXTENSIONS: []
ANSIBLE_ANSIBLE_LINT_FILE_NAMES_REGEX:
  - "main.yml"
ANSIBLE_DIRECTORY: "tasks"
