---
- name: Setup SSM config in ~/.ssh/config
  ansible.builtin.lineinfile:
    path: ~/.ssh/config
    line: |-
      # SSH over Session Manager
      host i-* mi-*
          ProxyCommand sh -c "aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
    create: yes
